create table cadastramento (id bigint generated by default as identity, cidade varchar(255), cpf varchar(255), nome varchar(255), estado varchar(255), primary key (id));
create table estados (id bigint generated by default as identity, estado varchar(255), primary key (id));

insert into cadastramento (nome, cpf, cidade, estado) values ('João da Silva', '11111111111', 'Recife', 'Pernambuco');
insert into cadastramento (nome, cpf, cidade, estado) values ('Helena Moura', '22222222222', 'Rio de Janeiro', 'Rio de Janeiro');
insert into cadastramento (nome, cpf, cidade, estado) values ('Rafael Furtado', '33333333333', 'Olinda', 'Pernambuco');
insert into cadastramento (nome, cpf, cidade, estado) values ('Jéssica Ribeiro', '44444444444', 'Paulista', 'Pernambuco');
insert into cadastramento (nome, cpf, cidade, estado) values ('Antônio Carlos', '55555555555', 'Aracaju', 'Sergipe');
insert into cadastramento (nome, cpf, cidade, estado) values ('José Maria', '66666666666', 'São Paulo', 'São Paulo');
insert into cadastramento (nome, cpf, cidade, estado) values ('Ana Clara', '77777777777', 'Fortaleza', 'Ceará');
insert into cadastramento (nome, cpf, cidade, estado) values ('Ricardo Pereira', '88888888888', 'Maceió', 'Alagoas');
insert into cadastramento (nome, cpf, cidade, estado) values ('Maria Lúcia', '99999999999', 'Recife', 'Pernambuco');
insert into cadastramento (nome, cpf, cidade, estado) values ('Thiago Santos', '00000000000', 'João Pessoa', 'Paraíba');

insert into estados (id, estado) values ('1', 'Pernambuco');
insert into estados (id, estado) values ('2', 'Paraíba');
insert into estados (id, estado) values ('3', 'Alagoas');
insert into estados (id, estado) values ('4', 'Sergipe');
insert into estados (id, estado) values ('5', 'Ceará');
insert into estados (id, estado) values ('6', 'São Paulo');
insert into estados (id, estado) values ('7', 'Rio de Janeiro');
